---
###-----------------------------------------Netdata_Global_Config----------------------------------------------
master_node_ip: 192.168.1.11

compute_01_ip: 192.168.1.12

compute_02_ip: 192.168.1.13

###-----------------------------------------Version Repository----------------------------------------------
opennebula_version: 5.9


one_hosts:
  - host: master-node
    ip: 192.168.1.11
  - host: compute-01
    ip: 192.168.1.12
  - host: compute-02
    ip: 192.168.1.13
