---
master-node: 192.168.1.11

# msi-mysql_root_pass >> if you already set the root password then assign it
# to this variable. by default there is no password.
msi_mysql_root_pass: ""

# msi-new_mysql_root_pass >> required. this will be the new mysql root password.
# if you don't want to change your old password then you can assign your old
# password to it too.
# oh and don't forget, always use ansible vault for sensitive data :)
msi_new_mysql_root_pass: "nikou123"


# Variables for opennebula
host_group: opennebula

opennebula_db: opennebula
opennebula_db_user: oneadmin
opennebula_db_pass: "nikou123"

oneadmin_password: "oneadmin"

