---
- name: Step 1. Add multiple repositories into the same file (1/2)
  yum_repository:
    file: opennebula
    name: opennebula
    description: package-install
    baseurl: https://downloads.opennebula.org/repo/5.4/CentOS/7/x86_64
    enabled: yes
    gpgkey: https://downloads.opennebula.org/repo/repo.key
    gpgcheck: yes
    state: present

- name: Step 2. yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no

- name: Step 3. Installing the Software
  yum:
    name: opennebula-node-kvm
    state: present


- name: Step 3. Newer QEMU/KVM <only CentOS/RHEL 7>
  yum:
    name: 
      - centos-release-qemu-ev
      - qemu-kvm 
    state: present

    
- name: install libvirtd.conf
  template: src=libvirtd.conf.j2  dest=/etc/libvirt/libvirtd.conf

#- name: Upload ssh config
#  copy: src=files/insecure_config dest=/var/lib/one/.ssh/config owner=oneadmin group=oneadmin mode=0600

- name: Recursively change ownership of a directory
  file:
    path: /var/lib/one/.ssh
    state: directory
    recurse: yes
    owner: oneadmin
    group: oneadmin
  become_user: oneadmin

- name: Step 4. Ensure OpenNbula  is running and starts on boot
  systemd:
    name: libvirtd
    state: restarted
    enabled: yes
