---
- hosts: all
  roles:
    - { role: requirement, tags: general-baremetal, become: yes, gather_facts: yes }


- hosts: openebula-database
  roles:
    - { role: mysql, tags: mysql, become: yes }


- hosts: openebula-master
  roles:
    - { role: openebula-frontend, tags: openebula, become: yes }


- hosts: compute-nodes
  roles:
    - { role: compute-nodes, tags: compute-nodes, become: yes }
    - { role: auth-node, tags: auth-node, become: yes }


#- hosts: ilo-reset-pass
#  roles:
#    - { role: ilo-pass, tags: ilo-pass, become: yes }

        
#- hosts: networks
#  roles:
#    - { role: one-network, tags: one-network, become: yes }
