---
- hosts: all 
  gather_facts: true
  roles:
    - role: requirement 
  tags: ['requirement']

- hosts: openebula-frontend 
  roles:
    - role: mysql
    - role: openebula-frontend
  tags: ['openebula-front']

- hosts: compute-nodes 
  gather_facts: true
  roles:
    - role: compute-nodes
  tags: ['compute-node']

- hosts: compute-nodes
  roles:
    - role: auth-node
  tags: ['auth-node']
