---
- import_tasks: install-redhat.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

- import_tasks: install-debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Ensure OpenNbula  is running and starts on boot 
  service:
    name: 
      - opennebula
      - opennebula-sunstone
      - opennebula-flow
      - opennebula-gate
      - opennebula-scheduler  
    state: restarted
    enabled: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

- name: check date
  command: date
  register: out
- debug:
    msg: "{{out.stdout}}"
- pause:
    prompt: "-----------Maka Sure Completion OpenNbula Frontend  is Completed-----------"
    seconds: 15

