---
- import_tasks: install-redhat.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

- import_tasks: install-debian.yml 
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: restart-ntpd
  systemd:
     name: ntpd
     state: restarted
     enabled: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

- name: /etc/hosts sets 
  template: src=templates/hosts.j2  dest=/etc/hosts owner=root group=root

- name: check date
  command: date
  register: out
- debug: 
    msg: "{{out.stdout}}"
- pause:
    prompt: "-----------Maka Sure Completion Base Installation OS Level is Completed-----------"
    seconds: 15


